import { registerEnumType } from "@nestjs/graphql";

enum ErrorCodes {
	// General
	ERROR = "ERROR",
	READ_ERROR = "READ_ERROR",
	CREATE_ERROR = "CREATE_ERROR",
	UPDATE_ERROR = "UPDATE_ERROR",
	DELETE_ERROR = "DELETE_ERROR",
	INACTIVE_REGISTER_RELATIONS = "INACTIVE_REGISTER_RELATIONS",
	HAS_ACTIVE_RELATIONS = "HAS_ACTIVE_RELATIONS",
	NOT_FOUND = "NOT_FOUND",
	// Employee
	MISSING_SCHEDULE = "MISSING_SCHEDULE",
	SCHEDULE_NOT_FOUND = "SCHEDULE_NOT_FOUND",
	SKILL_NOT_FOUND = "SKILL_NOT_FOUND",
}
export default ErrorCodes;
registerEnumType(ErrorCodes, { name: "ErrorCodes" });
